version: "3.9"
services:
  bot:
    build: .
    command: python bot.py
    env_file: .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:6
    
